/*
SQLyog v10.2 
MySQL - 5.7.9-log : Database - db_hdb_passport
*********************************************************************
*/


/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`db_hdb_passport` /*!40100 DEFAULT CHARACTER SET utf8 */;
USE db_hdb_passport;

DROP TABLE IF EXISTS `conn_test`;

CREATE TABLE `conn_test` (
  `a` char(1) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS `passport_user_1`;
DROP TABLE IF EXISTS `passport_user_2`;
DROP TABLE IF EXISTS `passport_user_3`;
DROP TABLE IF EXISTS `passport_user_4`;
DROP TABLE IF EXISTS `passport_user_5`;
DROP TABLE IF EXISTS `passport_user_6`;
DROP TABLE IF EXISTS `passport_user_7`;
DROP TABLE IF EXISTS `passport_user_8`;
DROP TABLE IF EXISTS `passport_user_9`;
DROP TABLE IF EXISTS `passport_user_10`;
DROP TABLE IF EXISTS `passport_user_11`;
DROP TABLE IF EXISTS `passport_user_12`;
DROP TABLE IF EXISTS `passport_user_13`;
DROP TABLE IF EXISTS `passport_user_14`;
DROP TABLE IF EXISTS `passport_user_15`;
DROP TABLE IF EXISTS `passport_user_16`;
DROP TABLE IF EXISTS `passport_user_17`;
DROP TABLE IF EXISTS `passport_user_18`;
DROP TABLE IF EXISTS `passport_user_19`;
DROP TABLE IF EXISTS `passport_user_20`;
DROP TABLE IF EXISTS `passport_user_21`;
DROP TABLE IF EXISTS `passport_user_22`;
DROP TABLE IF EXISTS `passport_user_23`;
DROP TABLE IF EXISTS `passport_user_24`;
DROP TABLE IF EXISTS `passport_user_25`;
DROP TABLE IF EXISTS `passport_user_26`;
DROP TABLE IF EXISTS `passport_user_27`;
DROP TABLE IF EXISTS `passport_user_28`;
DROP TABLE IF EXISTS `passport_user_29`;
DROP TABLE IF EXISTS `passport_user_30`;
DROP TABLE IF EXISTS `passport_user_31`;
DROP TABLE IF EXISTS `passport_user_32`;


CREATE TABLE `passport_user_1` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(36) NOT NULL DEFAULT '' COMMENT '用户登录名',
  `password` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '用户密码',
  `salt` VARCHAR(5) NOT NULL DEFAULT '' COMMENT 'salt',
  `telephone` VARCHAR(16) NOT NULL DEFAULT '' COMMENT '移动电话号码',
  `email` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '邮箱',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '用户创建的时间',
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=100000000 DEFAULT CHARSET=utf8 COMMENT='用户基本信息';

CREATE TABLE `passport_user_2` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(36) NOT NULL DEFAULT '' COMMENT '用户登录名',
  `password` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '用户密码',
  `salt` VARCHAR(5) NOT NULL DEFAULT '' COMMENT 'salt',
  `telephone` VARCHAR(16) NOT NULL DEFAULT '' COMMENT '移动电话号码',
  `email` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '邮箱',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '用户创建的时间',
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=200000000 DEFAULT CHARSET=utf8 COMMENT='用户基本信息';

CREATE TABLE `passport_user_3` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(36) NOT NULL DEFAULT '' COMMENT '用户登录名',
  `password` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '用户密码',
  `salt` VARCHAR(5) NOT NULL DEFAULT '' COMMENT 'salt',
  `telephone` VARCHAR(16) NOT NULL DEFAULT '' COMMENT '移动电话号码',
  `email` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '邮箱',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '用户创建的时间',
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=300000000 DEFAULT CHARSET=utf8 COMMENT='用户基本信息';

CREATE TABLE `passport_user_4` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(36) NOT NULL DEFAULT '' COMMENT '用户登录名',
  `password` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '用户密码',
  `salt` VARCHAR(5) NOT NULL DEFAULT '' COMMENT 'salt',
  `telephone` VARCHAR(16) NOT NULL DEFAULT '' COMMENT '移动电话号码',
  `email` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '邮箱',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '用户创建的时间',
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=400000000 DEFAULT CHARSET=utf8 COMMENT='用户基本信息';

CREATE TABLE `passport_user_5` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(36) NOT NULL DEFAULT '' COMMENT '用户登录名',
  `password` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '用户密码',
  `salt` VARCHAR(5) NOT NULL DEFAULT '' COMMENT 'salt',
  `telephone` VARCHAR(16) NOT NULL DEFAULT '' COMMENT '移动电话号码',
  `email` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '邮箱',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '用户创建的时间',
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=500000000 DEFAULT CHARSET=utf8 COMMENT='用户基本信息';

CREATE TABLE `passport_user_6` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(36) NOT NULL DEFAULT '' COMMENT '用户登录名',
  `password` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '用户密码',
  `salt` VARCHAR(5) NOT NULL DEFAULT '' COMMENT 'salt',
  `telephone` VARCHAR(16) NOT NULL DEFAULT '' COMMENT '移动电话号码',
  `email` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '邮箱',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '用户创建的时间',
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=600000000 DEFAULT CHARSET=utf8 COMMENT='用户基本信息';

CREATE TABLE `passport_user_7` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(36) NOT NULL DEFAULT '' COMMENT '用户登录名',
  `password` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '用户密码',
  `salt` VARCHAR(5) NOT NULL DEFAULT '' COMMENT 'salt',
  `telephone` VARCHAR(16) NOT NULL DEFAULT '' COMMENT '移动电话号码',
  `email` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '邮箱',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '用户创建的时间',
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=700000000 DEFAULT CHARSET=utf8 COMMENT='用户基本信息';

CREATE TABLE `passport_user_8` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(36) NOT NULL DEFAULT '' COMMENT '用户登录名',
  `password` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '用户密码',
  `salt` VARCHAR(5) NOT NULL DEFAULT '' COMMENT 'salt',
  `telephone` VARCHAR(16) NOT NULL DEFAULT '' COMMENT '移动电话号码',
  `email` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '邮箱',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '用户创建的时间',
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=800000000 DEFAULT CHARSET=utf8 COMMENT='用户基本信息';

CREATE TABLE `passport_user_9` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(36) NOT NULL DEFAULT '' COMMENT '用户登录名',
  `password` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '用户密码',
  `salt` VARCHAR(5) NOT NULL DEFAULT '' COMMENT 'salt',
  `telephone` VARCHAR(16) NOT NULL DEFAULT '' COMMENT '移动电话号码',
  `email` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '邮箱',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '用户创建的时间',
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=900000000 DEFAULT CHARSET=utf8 COMMENT='用户基本信息';

CREATE TABLE `passport_user_10` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(36) NOT NULL DEFAULT '' COMMENT '用户登录名',
  `password` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '用户密码',
  `salt` VARCHAR(5) NOT NULL DEFAULT '' COMMENT 'salt',
  `telephone` VARCHAR(16) NOT NULL DEFAULT '' COMMENT '移动电话号码',
  `email` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '邮箱',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '用户创建的时间',
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=1000000000 DEFAULT CHARSET=utf8 COMMENT='用户基本信息';

CREATE TABLE `passport_user_11` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(36) NOT NULL DEFAULT '' COMMENT '用户登录名',
  `password` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '用户密码',
  `salt` VARCHAR(5) NOT NULL DEFAULT '' COMMENT 'salt',
  `telephone` VARCHAR(16) NOT NULL DEFAULT '' COMMENT '移动电话号码',
  `email` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '邮箱',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '用户创建的时间',
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=1100000000 DEFAULT CHARSET=utf8 COMMENT='用户基本信息';

CREATE TABLE `passport_user_12` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(36) NOT NULL DEFAULT '' COMMENT '用户登录名',
  `password` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '用户密码',
  `salt` VARCHAR(5) NOT NULL DEFAULT '' COMMENT 'salt',
  `telephone` VARCHAR(16) NOT NULL DEFAULT '' COMMENT '移动电话号码',
  `email` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '邮箱',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '用户创建的时间',
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=1200000000 DEFAULT CHARSET=utf8 COMMENT='用户基本信息';

CREATE TABLE `passport_user_13` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(36) NOT NULL DEFAULT '' COMMENT '用户登录名',
  `password` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '用户密码',
  `salt` VARCHAR(5) NOT NULL DEFAULT '' COMMENT 'salt',
  `telephone` VARCHAR(16) NOT NULL DEFAULT '' COMMENT '移动电话号码',
  `email` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '邮箱',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '用户创建的时间',
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=1300000000 DEFAULT CHARSET=utf8 COMMENT='用户基本信息';

CREATE TABLE `passport_user_14` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(36) NOT NULL DEFAULT '' COMMENT '用户登录名',
  `password` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '用户密码',
  `salt` VARCHAR(5) NOT NULL DEFAULT '' COMMENT 'salt',
  `telephone` VARCHAR(16) NOT NULL DEFAULT '' COMMENT '移动电话号码',
  `email` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '邮箱',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '用户创建的时间',
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=1400000000 DEFAULT CHARSET=utf8 COMMENT='用户基本信息';

CREATE TABLE `passport_user_15` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(36) NOT NULL DEFAULT '' COMMENT '用户登录名',
  `password` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '用户密码',
  `salt` VARCHAR(5) NOT NULL DEFAULT '' COMMENT 'salt',
  `telephone` VARCHAR(16) NOT NULL DEFAULT '' COMMENT '移动电话号码',
  `email` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '邮箱',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '用户创建的时间',
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=1500000000 DEFAULT CHARSET=utf8 COMMENT='用户基本信息';

CREATE TABLE `passport_user_16` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(36) NOT NULL DEFAULT '' COMMENT '用户登录名',
  `password` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '用户密码',
  `salt` VARCHAR(5) NOT NULL DEFAULT '' COMMENT 'salt',
  `telephone` VARCHAR(16) NOT NULL DEFAULT '' COMMENT '移动电话号码',
  `email` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '邮箱',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '用户创建的时间',
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=1600000000 DEFAULT CHARSET=utf8 COMMENT='用户基本信息';

CREATE TABLE `passport_user_17` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(36) NOT NULL DEFAULT '' COMMENT '用户登录名',
  `password` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '用户密码',
  `salt` VARCHAR(5) NOT NULL DEFAULT '' COMMENT 'salt',
  `telephone` VARCHAR(16) NOT NULL DEFAULT '' COMMENT '移动电话号码',
  `email` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '邮箱',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '用户创建的时间',
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=1700000000 DEFAULT CHARSET=utf8 COMMENT='用户基本信息';

CREATE TABLE `passport_user_18` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(36) NOT NULL DEFAULT '' COMMENT '用户登录名',
  `password` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '用户密码',
  `salt` VARCHAR(5) NOT NULL DEFAULT '' COMMENT 'salt',
  `telephone` VARCHAR(16) NOT NULL DEFAULT '' COMMENT '移动电话号码',
  `email` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '邮箱',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '用户创建的时间',
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=1800000000 DEFAULT CHARSET=utf8 COMMENT='用户基本信息';

CREATE TABLE `passport_user_19` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(36) NOT NULL DEFAULT '' COMMENT '用户登录名',
  `password` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '用户密码',
  `salt` VARCHAR(5) NOT NULL DEFAULT '' COMMENT 'salt',
  `telephone` VARCHAR(16) NOT NULL DEFAULT '' COMMENT '移动电话号码',
  `email` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '邮箱',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '用户创建的时间',
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=1900000000 DEFAULT CHARSET=utf8 COMMENT='用户基本信息';

CREATE TABLE `passport_user_20` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(36) NOT NULL DEFAULT '' COMMENT '用户登录名',
  `password` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '用户密码',
  `salt` VARCHAR(5) NOT NULL DEFAULT '' COMMENT 'salt',
  `telephone` VARCHAR(16) NOT NULL DEFAULT '' COMMENT '移动电话号码',
  `email` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '邮箱',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '用户创建的时间',
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=2000000000 DEFAULT CHARSET=utf8 COMMENT='用户基本信息';

CREATE TABLE `passport_user_21` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(36) NOT NULL DEFAULT '' COMMENT '用户登录名',
  `password` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '用户密码',
  `salt` VARCHAR(5) NOT NULL DEFAULT '' COMMENT 'salt',
  `telephone` VARCHAR(16) NOT NULL DEFAULT '' COMMENT '移动电话号码',
  `email` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '邮箱',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '用户创建的时间',
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=2100000000 DEFAULT CHARSET=utf8 COMMENT='用户基本信息';

CREATE TABLE `passport_user_22` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(36) NOT NULL DEFAULT '' COMMENT '用户登录名',
  `password` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '用户密码',
  `salt` VARCHAR(5) NOT NULL DEFAULT '' COMMENT 'salt',
  `telephone` VARCHAR(16) NOT NULL DEFAULT '' COMMENT '移动电话号码',
  `email` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '邮箱',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '用户创建的时间',
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=2200000000 DEFAULT CHARSET=utf8 COMMENT='用户基本信息';

CREATE TABLE `passport_user_23` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(36) NOT NULL DEFAULT '' COMMENT '用户登录名',
  `password` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '用户密码',
  `salt` VARCHAR(5) NOT NULL DEFAULT '' COMMENT 'salt',
  `telephone` VARCHAR(16) NOT NULL DEFAULT '' COMMENT '移动电话号码',
  `email` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '邮箱',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '用户创建的时间',
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=2300000000 DEFAULT CHARSET=utf8 COMMENT='用户基本信息';

CREATE TABLE `passport_user_24` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(36) NOT NULL DEFAULT '' COMMENT '用户登录名',
  `password` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '用户密码',
  `salt` VARCHAR(5) NOT NULL DEFAULT '' COMMENT 'salt',
  `telephone` VARCHAR(16) NOT NULL DEFAULT '' COMMENT '移动电话号码',
  `email` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '邮箱',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '用户创建的时间',
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=2400000000 DEFAULT CHARSET=utf8 COMMENT='用户基本信息';

CREATE TABLE `passport_user_25` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(36) NOT NULL DEFAULT '' COMMENT '用户登录名',
  `password` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '用户密码',
  `salt` VARCHAR(5) NOT NULL DEFAULT '' COMMENT 'salt',
  `telephone` VARCHAR(16) NOT NULL DEFAULT '' COMMENT '移动电话号码',
  `email` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '邮箱',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '用户创建的时间',
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=2500000000 DEFAULT CHARSET=utf8 COMMENT='用户基本信息';

CREATE TABLE `passport_user_26` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(36) NOT NULL DEFAULT '' COMMENT '用户登录名',
  `password` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '用户密码',
  `salt` VARCHAR(5) NOT NULL DEFAULT '' COMMENT 'salt',
  `telephone` VARCHAR(16) NOT NULL DEFAULT '' COMMENT '移动电话号码',
  `email` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '邮箱',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '用户创建的时间',
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=2600000000 DEFAULT CHARSET=utf8 COMMENT='用户基本信息';

CREATE TABLE `passport_user_27` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(36) NOT NULL DEFAULT '' COMMENT '用户登录名',
  `password` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '用户密码',
  `salt` VARCHAR(5) NOT NULL DEFAULT '' COMMENT 'salt',
  `telephone` VARCHAR(16) NOT NULL DEFAULT '' COMMENT '移动电话号码',
  `email` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '邮箱',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '用户创建的时间',
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=2700000000 DEFAULT CHARSET=utf8 COMMENT='用户基本信息';

CREATE TABLE `passport_user_28` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(36) NOT NULL DEFAULT '' COMMENT '用户登录名',
  `password` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '用户密码',
  `salt` VARCHAR(5) NOT NULL DEFAULT '' COMMENT 'salt',
  `telephone` VARCHAR(16) NOT NULL DEFAULT '' COMMENT '移动电话号码',
  `email` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '邮箱',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '用户创建的时间',
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=2800000000 DEFAULT CHARSET=utf8 COMMENT='用户基本信息';

CREATE TABLE `passport_user_29` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(36) NOT NULL DEFAULT '' COMMENT '用户登录名',
  `password` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '用户密码',
  `salt` VARCHAR(5) NOT NULL DEFAULT '' COMMENT 'salt',
  `telephone` VARCHAR(16) NOT NULL DEFAULT '' COMMENT '移动电话号码',
  `email` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '邮箱',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '用户创建的时间',
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=2900000000 DEFAULT CHARSET=utf8 COMMENT='用户基本信息';

CREATE TABLE `passport_user_30` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(36) NOT NULL DEFAULT '' COMMENT '用户登录名',
  `password` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '用户密码',
  `salt` VARCHAR(5) NOT NULL DEFAULT '' COMMENT 'salt',
  `telephone` VARCHAR(16) NOT NULL DEFAULT '' COMMENT '移动电话号码',
  `email` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '邮箱',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '用户创建的时间',
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=3000000000 DEFAULT CHARSET=utf8 COMMENT='用户基本信息';

CREATE TABLE `passport_user_31` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(36) NOT NULL DEFAULT '' COMMENT '用户登录名',
  `password` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '用户密码',
  `salt` VARCHAR(5) NOT NULL DEFAULT '' COMMENT 'salt',
  `telephone` VARCHAR(16) NOT NULL DEFAULT '' COMMENT '移动电话号码',
  `email` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '邮箱',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '用户创建的时间',
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=3100000000 DEFAULT CHARSET=utf8 COMMENT='用户基本信息';

CREATE TABLE `passport_user_32` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(36) NOT NULL DEFAULT '' COMMENT '用户登录名',
  `password` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '用户密码',
  `salt` VARCHAR(5) NOT NULL DEFAULT '' COMMENT 'salt',
  `telephone` VARCHAR(16) NOT NULL DEFAULT '' COMMENT '移动电话号码',
  `email` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '邮箱',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '用户创建的时间',
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=3200000000 DEFAULT CHARSET=utf8 COMMENT='用户基本信息';
