CREATE SCHEMA IF NOT EXISTS db_hdb_guess
  DEFAULT CHARACTER SET utf8
  COLLATE utf8_general_ci;
USE db_hdb_guess;

DROP TABLE IF EXISTS `conn_test`;

CREATE TABLE `conn_test` (
  `a` char(1) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS guess_match;
CREATE TABLE `guess_match` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `external_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '第三方数据中比赛的id',
  `league_name` VARCHAR(50) NOT NULL DEFAULT "" COMMENT '联赛名称',
  `match_phase` VARCHAR(50) NOT NULL DEFAULT "" COMMENT '联赛阶段',
  `home_team_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '主队的id',
  `guest_team_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '客队的id',
  `begin_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '比赛开始时间',  
  `status` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '比赛状态：0代表未开始，1代表进行中，2代表已结束, 3代表已经开奖', 
  `home_score` TINYINT(2) NOT NULL DEFAULT '0' COMMENT '主队最终得分',
  `guest_score` TINYINT(2) NOT NULL DEFAULT '0' COMMENT '客队最终得分',
  `online_flag` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '上架标志位：0代表下架，1代表上架', 
  `delete_flag` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '删除标志位：0代表未删除，1代表已删除', 
  `creator` VARCHAR(50) NOT NULL DEFAULT "系统" COMMENT '记录添加者',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录添加时间',  
  `updater` VARCHAR(50) NOT NULL DEFAULT "系统" COMMENT '记录更新者',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '记录更新时间',   
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_guess_match_external_id` (`external_id`),
  INDEX idx_guess_match_home_team_id (`home_team_id`),
  INDEX idx_guess_match_guest_team_id(`guest_team_id`)
) ENGINE=INNODB AUTO_INCREMENT=100000000000 DEFAULT CHARSET=utf8 COMMENT='猜球比赛表';

DROP TABLE IF EXISTS guess_team;
CREATE TABLE `guess_team` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `external_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '第三方数据中队的id',
  `name` varchar(255) NOT NULL DEFAULT '' COMMENT '队名',
  `english_name` varchar(255) NOT NULL DEFAULT '' COMMENT '英文队名',
  `logo` varchar(255) NOT NULL DEFAULT '' COMMENT '队徽',
  `delete_flag` tinyint(1) NOT NULL DEFAULT '0' COMMENT '删除标志位：0代表未删除，1代表已删除', 
  `creator` varchar(50) NOT NULL DEFAULT "系统" COMMENT '记录添加者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录添加时间',  
  `updater` varchar(50) NOT NULL DEFAULT "系统" COMMENT '记录更新者',
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '记录更新时间',   
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_guess_team_external_id` (`external_id`)
) ENGINE=InnoDB AUTO_INCREMENT=100000000000 DEFAULT CHARSET=utf8 COMMENT='猜球球队表';

DROP TABLE IF EXISTS guess_bet_item;
CREATE TABLE `guess_bet_item` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '投注类型：胜平负；比分等等',
  `name` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '投注项的名称：胜、平、负、1:1等等',
  `match_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '该投注项所关联的比赛Id',
  `result` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '比赛结果是否与该投注项匹配：0代表不匹配，1代表匹配', 
  `odds` DECIMAL(5,2) NOT NULL DEFAULT '-1.00' COMMENT '比赛最终的赔率，用于查看历史比赛的时候用', 
  `odds_status` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '赔率变化状态：0代表不变，1代表上升，2代表下降',
  `delete_flag` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '删除标志位：0代表未删除，1代表已删除', 
  `creator` VARCHAR(50) NOT NULL DEFAULT "系统" COMMENT '记录添加者',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录添加时间',  
  `updater` VARCHAR(50) NOT NULL DEFAULT "系统" COMMENT '记录更新者',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '记录更新时间',   
  PRIMARY KEY (`id`),
  INDEX idx_guess_bet_item_match_id(`match_id`)
) ENGINE=INNODB AUTO_INCREMENT=100000000000 DEFAULT CHARSET=utf8 COMMENT='猜球投注项表';

DROP TABLE IF EXISTS guess_config;
CREATE TABLE `guess_config`(
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `config_key` VARCHAR(255) NOT NULL DEFAULT "" COMMENT '配置key',
  `config_value` VARCHAR(255) NOT NULL DEFAULT "" COMMENT '配置value',
  `delete_flag` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '删除标志位：0代表未删除，1代表已删除', 
  `creator` VARCHAR(50) NOT NULL DEFAULT "系统" COMMENT '记录添加者',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录添加时间',  
  `updater` VARCHAR(50) NOT NULL DEFAULT "系统" COMMENT '记录更新者',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '记录更新时间',   
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_guess_config_config_key` (`config_key`)
) ENGINE=INNODB AUTO_INCREMENT=100000000000 DEFAULT CHARSET=utf8 COMMENT='猜球配置项表';

DROP TABLE IF EXISTS guess_bet_00;
CREATE TABLE `guess_bet_00` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '下注的用户id',
  `match_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '所下注的比赛id',
  `home_team_name` varchar(255) NOT NULL DEFAULT '' COMMENT '主队名',
  `home_team_logo` varchar(255) NOT NULL DEFAULT '' COMMENT '主队徽',
  `guest_team_name` varchar(255) NOT NULL DEFAULT '' COMMENT '客队名',
  `guest_team_logo` varchar(255) NOT NULL DEFAULT '' COMMENT '客队徽',
  `bet_item_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '下注时所选的下注项id',
  `bet_item_name` varchar(255) NOT NULL DEFAULT '' COMMENT '下注是所选的下注项的名称',
  `bet_points` INT(10) NOT NULL DEFAULT '0' COMMENT '所下的注数', 
  `odds` DECIMAL(5,2) NOT NULL DEFAULT '0.00' COMMENT '下注时的赔率', 
  `status` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '投注的状态，0代表未开奖、1代表已中奖、2代表未中奖',
  `win_bet_item_name` varchar(255) NOT NULL DEFAULT '' COMMENT '最终胜出的投注项名称',
  `win_points` INT(10) NULL DEFAULT '0' COMMENT '所赢得的总的积分',
  `pay_txn_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '所支付积分id',
  `recv_txn_id` BIGINT(20) NULL DEFAULT '0' COMMENT '所赢积分id',
  `phone_number` VARCHAR(20) NOT NULL DEFAULT "0" COMMENT '下注者电话',
  `delete_flag` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '删除标志位：0代表未删除，1代表已删除', 
  `creator` VARCHAR(50) NOT NULL DEFAULT "系统" COMMENT '记录添加者',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录添加时间',  
  `updater` VARCHAR(50) NOT NULL DEFAULT "系统" COMMENT '记录更新者',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '记录更新时间',   
  PRIMARY KEY (`id`),
  INDEX idx_guess_bet_match_id(`match_id`),
  INDEX idx_guess_user_id(`user_id`)
) ENGINE=INNODB AUTO_INCREMENT=100000000000 DEFAULT CHARSET=utf8 COMMENT='猜球投注表';

DROP TABLE IF EXISTS guess_bet_01;
CREATE TABLE `guess_bet_01` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '下注的用户id',
  `match_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '所下注的比赛id',
  `home_team_name` varchar(255) NOT NULL DEFAULT '' COMMENT '主队名',
  `home_team_logo` varchar(255) NOT NULL DEFAULT '' COMMENT '主队徽',
  `guest_team_name` varchar(255) NOT NULL DEFAULT '' COMMENT '客队名',
  `guest_team_logo` varchar(255) NOT NULL DEFAULT '' COMMENT '客队徽',
  `bet_item_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '下注时所选的下注项id',
  `bet_item_name` varchar(255) NOT NULL DEFAULT '' COMMENT '下注是所选的下注项的名称',
  `bet_points` INT(10) NOT NULL DEFAULT '0' COMMENT '所下的注数', 
  `odds` DECIMAL(5,2) NOT NULL DEFAULT '0.00' COMMENT '下注时的赔率', 
  `status` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '投注的状态，0代表未开奖、1代表已中奖、2代表未中奖',
  `win_bet_item_name` varchar(255) NOT NULL DEFAULT '' COMMENT '最终胜出的投注项名称',
  `win_points` INT(10) NULL DEFAULT '0' COMMENT '所赢得的总的积分',
  `pay_txn_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '所支付积分id',
  `recv_txn_id` BIGINT(20) NULL DEFAULT '0' COMMENT '所赢积分id',
  `phone_number` VARCHAR(20) NOT NULL DEFAULT "0" COMMENT '下注者电话',
  `delete_flag` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '删除标志位：0代表未删除，1代表已删除', 
  `creator` VARCHAR(50) NOT NULL DEFAULT "系统" COMMENT '记录添加者',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录添加时间',  
  `updater` VARCHAR(50) NOT NULL DEFAULT "系统" COMMENT '记录更新者',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '记录更新时间',   
  PRIMARY KEY (`id`),
  INDEX idx_guess_bet_match_id(`match_id`),
  INDEX idx_guess_user_id(`user_id`)
) ENGINE=INNODB AUTO_INCREMENT=110000000000 DEFAULT CHARSET=utf8 COMMENT='猜球投注表';

DROP TABLE IF EXISTS guess_bet_02;
CREATE TABLE `guess_bet_02` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '下注的用户id',
  `match_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '所下注的比赛id',
  `home_team_name` varchar(255) NOT NULL DEFAULT '' COMMENT '主队名',
  `home_team_logo` varchar(255) NOT NULL DEFAULT '' COMMENT '主队徽',
  `guest_team_name` varchar(255) NOT NULL DEFAULT '' COMMENT '客队名',
  `guest_team_logo` varchar(255) NOT NULL DEFAULT '' COMMENT '客队徽',
  `bet_item_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '下注时所选的下注项id',
  `bet_item_name` varchar(255) NOT NULL DEFAULT '' COMMENT '下注是所选的下注项的名称',
  `bet_points` INT(10) NOT NULL DEFAULT '0' COMMENT '所下的注数', 
  `odds` DECIMAL(5,2) NOT NULL DEFAULT '0.00' COMMENT '下注时的赔率', 
  `status` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '投注的状态，0代表未开奖、1代表已中奖、2代表未中奖',
  `win_bet_item_name` varchar(255) NOT NULL DEFAULT '' COMMENT '最终胜出的投注项名称',
  `win_points` INT(10) NULL DEFAULT '0' COMMENT '所赢得的总的积分',
  `pay_txn_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '所支付积分id',
  `recv_txn_id` BIGINT(20) NULL DEFAULT '0' COMMENT '所赢积分id',
  `phone_number` VARCHAR(20) NOT NULL DEFAULT "0" COMMENT '下注者电话',
  `delete_flag` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '删除标志位：0代表未删除，1代表已删除', 
  `creator` VARCHAR(50) NOT NULL DEFAULT "系统" COMMENT '记录添加者',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录添加时间',  
  `updater` VARCHAR(50) NOT NULL DEFAULT "系统" COMMENT '记录更新者',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '记录更新时间',   
  PRIMARY KEY (`id`),
  INDEX idx_guess_bet_match_id(`match_id`),
  INDEX idx_guess_user_id(`user_id`)
) ENGINE=INNODB AUTO_INCREMENT=120000000000 DEFAULT CHARSET=utf8 COMMENT='猜球投注表';

DROP TABLE IF EXISTS guess_bet_03;
CREATE TABLE `guess_bet_03` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '下注的用户id',
  `match_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '所下注的比赛id',
  `home_team_name` varchar(255) NOT NULL DEFAULT '' COMMENT '主队名',
  `home_team_logo` varchar(255) NOT NULL DEFAULT '' COMMENT '主队徽',
  `guest_team_name` varchar(255) NOT NULL DEFAULT '' COMMENT '客队名',
  `guest_team_logo` varchar(255) NOT NULL DEFAULT '' COMMENT '客队徽',
  `bet_item_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '下注时所选的下注项id',
  `bet_item_name` varchar(255) NOT NULL DEFAULT '' COMMENT '下注是所选的下注项的名称',
  `bet_points` INT(10) NOT NULL DEFAULT '0' COMMENT '所下的注数', 
  `odds` DECIMAL(5,2) NOT NULL DEFAULT '0.00' COMMENT '下注时的赔率', 
  `status` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '投注的状态，0代表未开奖、1代表已中奖、2代表未中奖',
  `win_bet_item_name` varchar(255) NOT NULL DEFAULT '' COMMENT '最终胜出的投注项名称',
  `win_points` INT(10) NULL DEFAULT '0' COMMENT '所赢得的总的积分',
  `pay_txn_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '所支付积分id',
  `recv_txn_id` BIGINT(20) NULL DEFAULT '0' COMMENT '所赢积分id',
  `phone_number` VARCHAR(20) NOT NULL DEFAULT "0" COMMENT '下注者电话',
  `delete_flag` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '删除标志位：0代表未删除，1代表已删除', 
  `creator` VARCHAR(50) NOT NULL DEFAULT "系统" COMMENT '记录添加者',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录添加时间',  
  `updater` VARCHAR(50) NOT NULL DEFAULT "系统" COMMENT '记录更新者',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '记录更新时间',   
  PRIMARY KEY (`id`),
  INDEX idx_guess_bet_match_id(`match_id`),
  INDEX idx_guess_user_id(`user_id`)
) ENGINE=INNODB AUTO_INCREMENT=130000000000 DEFAULT CHARSET=utf8 COMMENT='猜球投注表';

DROP TABLE IF EXISTS guess_bet_04;
CREATE TABLE `guess_bet_04` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '下注的用户id',
  `match_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '所下注的比赛id',
  `home_team_name` varchar(255) NOT NULL DEFAULT '' COMMENT '主队名',
  `home_team_logo` varchar(255) NOT NULL DEFAULT '' COMMENT '主队徽',
  `guest_team_name` varchar(255) NOT NULL DEFAULT '' COMMENT '客队名',
  `guest_team_logo` varchar(255) NOT NULL DEFAULT '' COMMENT '客队徽',
  `bet_item_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '下注时所选的下注项id',
  `bet_item_name` varchar(255) NOT NULL DEFAULT '' COMMENT '下注是所选的下注项的名称',
  `bet_points` INT(10) NOT NULL DEFAULT '0' COMMENT '所下的注数', 
  `odds` DECIMAL(5,2) NOT NULL DEFAULT '0.00' COMMENT '下注时的赔率', 
  `status` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '投注的状态，0代表未开奖、1代表已中奖、2代表未中奖',
  `win_bet_item_name` varchar(255) NOT NULL DEFAULT '' COMMENT '最终胜出的投注项名称',
  `win_points` INT(10) NULL DEFAULT '0' COMMENT '所赢得的总的积分',
  `pay_txn_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '所支付积分id',
  `recv_txn_id` BIGINT(20) NULL DEFAULT '0' COMMENT '所赢积分id',
  `phone_number` VARCHAR(20) NOT NULL DEFAULT "0" COMMENT '下注者电话',
  `delete_flag` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '删除标志位：0代表未删除，1代表已删除', 
  `creator` VARCHAR(50) NOT NULL DEFAULT "系统" COMMENT '记录添加者',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录添加时间',  
  `updater` VARCHAR(50) NOT NULL DEFAULT "系统" COMMENT '记录更新者',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '记录更新时间',   
  PRIMARY KEY (`id`),
  INDEX idx_guess_bet_match_id(`match_id`),
  INDEX idx_guess_user_id(`user_id`)
) ENGINE=INNODB AUTO_INCREMENT=140000000000 DEFAULT CHARSET=utf8 COMMENT='猜球投注表';

DROP TABLE IF EXISTS guess_bet_05;
CREATE TABLE `guess_bet_05` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '下注的用户id',
  `match_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '所下注的比赛id',
  `home_team_name` varchar(255) NOT NULL DEFAULT '' COMMENT '主队名',
  `home_team_logo` varchar(255) NOT NULL DEFAULT '' COMMENT '主队徽',
  `guest_team_name` varchar(255) NOT NULL DEFAULT '' COMMENT '客队名',
  `guest_team_logo` varchar(255) NOT NULL DEFAULT '' COMMENT '客队徽',
  `bet_item_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '下注时所选的下注项id',
  `bet_item_name` varchar(255) NOT NULL DEFAULT '' COMMENT '下注是所选的下注项的名称',
  `bet_points` INT(10) NOT NULL DEFAULT '0' COMMENT '所下的注数', 
  `odds` DECIMAL(5,2) NOT NULL DEFAULT '0.00' COMMENT '下注时的赔率', 
  `status` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '投注的状态，0代表未开奖、1代表已中奖、2代表未中奖',
  `win_bet_item_name` varchar(255) NOT NULL DEFAULT '' COMMENT '最终胜出的投注项名称',
  `win_points` INT(10) NULL DEFAULT '0' COMMENT '所赢得的总的积分',
  `pay_txn_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '所支付积分id',
  `recv_txn_id` BIGINT(20) NULL DEFAULT '0' COMMENT '所赢积分id',
  `phone_number` VARCHAR(20) NOT NULL DEFAULT "0" COMMENT '下注者电话',
  `delete_flag` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '删除标志位：0代表未删除，1代表已删除', 
  `creator` VARCHAR(50) NOT NULL DEFAULT "系统" COMMENT '记录添加者',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录添加时间',  
  `updater` VARCHAR(50) NOT NULL DEFAULT "系统" COMMENT '记录更新者',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '记录更新时间',   
  PRIMARY KEY (`id`),
  INDEX idx_guess_bet_match_id(`match_id`),
  INDEX idx_guess_user_id(`user_id`)
) ENGINE=INNODB AUTO_INCREMENT=150000000000 DEFAULT CHARSET=utf8 COMMENT='猜球投注表';

DROP TABLE IF EXISTS guess_bet_06;
CREATE TABLE `guess_bet_06` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '下注的用户id',
  `match_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '所下注的比赛id',
  `home_team_name` varchar(255) NOT NULL DEFAULT '' COMMENT '主队名',
  `home_team_logo` varchar(255) NOT NULL DEFAULT '' COMMENT '主队徽',
  `guest_team_name` varchar(255) NOT NULL DEFAULT '' COMMENT '客队名',
  `guest_team_logo` varchar(255) NOT NULL DEFAULT '' COMMENT '客队徽',
  `bet_item_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '下注时所选的下注项id',
  `bet_item_name` varchar(255) NOT NULL DEFAULT '' COMMENT '下注是所选的下注项的名称',
  `bet_points` INT(10) NOT NULL DEFAULT '0' COMMENT '所下的注数', 
  `odds` DECIMAL(5,2) NOT NULL DEFAULT '0.00' COMMENT '下注时的赔率', 
  `status` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '投注的状态，0代表未开奖、1代表已中奖、2代表未中奖',
  `win_bet_item_name` varchar(255) NOT NULL DEFAULT '' COMMENT '最终胜出的投注项名称',
  `win_points` INT(10) NULL DEFAULT '0' COMMENT '所赢得的总的积分',
  `pay_txn_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '所支付积分id',
  `recv_txn_id` BIGINT(20) NULL DEFAULT '0' COMMENT '所赢积分id',
  `phone_number` VARCHAR(20) NOT NULL DEFAULT "0" COMMENT '下注者电话',
  `delete_flag` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '删除标志位：0代表未删除，1代表已删除', 
  `creator` VARCHAR(50) NOT NULL DEFAULT "系统" COMMENT '记录添加者',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录添加时间',  
  `updater` VARCHAR(50) NOT NULL DEFAULT "系统" COMMENT '记录更新者',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '记录更新时间',   
  PRIMARY KEY (`id`),
  INDEX idx_guess_bet_match_id(`match_id`),
  INDEX idx_guess_user_id(`user_id`)
) ENGINE=INNODB AUTO_INCREMENT=160000000000 DEFAULT CHARSET=utf8 COMMENT='猜球投注表';

DROP TABLE IF EXISTS guess_bet_07;
CREATE TABLE `guess_bet_07` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '下注的用户id',
  `match_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '所下注的比赛id',
  `home_team_name` varchar(255) NOT NULL DEFAULT '' COMMENT '主队名',
  `home_team_logo` varchar(255) NOT NULL DEFAULT '' COMMENT '主队徽',
  `guest_team_name` varchar(255) NOT NULL DEFAULT '' COMMENT '客队名',
  `guest_team_logo` varchar(255) NOT NULL DEFAULT '' COMMENT '客队徽',
  `bet_item_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '下注时所选的下注项id',
  `bet_item_name` varchar(255) NOT NULL DEFAULT '' COMMENT '下注是所选的下注项的名称',
  `bet_points` INT(10) NOT NULL DEFAULT '0' COMMENT '所下的注数', 
  `odds` DECIMAL(5,2) NOT NULL DEFAULT '0.00' COMMENT '下注时的赔率', 
  `status` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '投注的状态，0代表未开奖、1代表已中奖、2代表未中奖',
  `win_bet_item_name` varchar(255) NOT NULL DEFAULT '' COMMENT '最终胜出的投注项名称',
  `win_points` INT(10) NULL DEFAULT '0' COMMENT '所赢得的总的积分',
  `pay_txn_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '所支付积分id',
  `recv_txn_id` BIGINT(20) NULL DEFAULT '0' COMMENT '所赢积分id',
  `phone_number` VARCHAR(20) NOT NULL DEFAULT "0" COMMENT '下注者电话',
  `delete_flag` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '删除标志位：0代表未删除，1代表已删除', 
  `creator` VARCHAR(50) NOT NULL DEFAULT "系统" COMMENT '记录添加者',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录添加时间',  
  `updater` VARCHAR(50) NOT NULL DEFAULT "系统" COMMENT '记录更新者',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '记录更新时间',   
  PRIMARY KEY (`id`),
  INDEX idx_guess_bet_match_id(`match_id`),
  INDEX idx_guess_user_id(`user_id`)
) ENGINE=INNODB AUTO_INCREMENT=170000000000 DEFAULT CHARSET=utf8 COMMENT='猜球投注表';

DROP TABLE IF EXISTS guess_bet_08;
CREATE TABLE `guess_bet_08` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '下注的用户id',
  `match_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '所下注的比赛id',
  `home_team_name` varchar(255) NOT NULL DEFAULT '' COMMENT '主队名',
  `home_team_logo` varchar(255) NOT NULL DEFAULT '' COMMENT '主队徽',
  `guest_team_name` varchar(255) NOT NULL DEFAULT '' COMMENT '客队名',
  `guest_team_logo` varchar(255) NOT NULL DEFAULT '' COMMENT '客队徽',
  `bet_item_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '下注时所选的下注项id',
  `bet_item_name` varchar(255) NOT NULL DEFAULT '' COMMENT '下注是所选的下注项的名称',
  `bet_points` INT(10) NOT NULL DEFAULT '0' COMMENT '所下的注数', 
  `odds` DECIMAL(5,2) NOT NULL DEFAULT '0.00' COMMENT '下注时的赔率', 
  `status` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '投注的状态，0代表未开奖、1代表已中奖、2代表未中奖',
  `win_bet_item_name` varchar(255) NOT NULL DEFAULT '' COMMENT '最终胜出的投注项名称',
  `win_points` INT(10) NULL DEFAULT '0' COMMENT '所赢得的总的积分',
  `pay_txn_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '所支付积分id',
  `recv_txn_id` BIGINT(20) NULL DEFAULT '0' COMMENT '所赢积分id',
  `phone_number` VARCHAR(20) NOT NULL DEFAULT "0" COMMENT '下注者电话',
  `delete_flag` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '删除标志位：0代表未删除，1代表已删除', 
  `creator` VARCHAR(50) NOT NULL DEFAULT "系统" COMMENT '记录添加者',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录添加时间',  
  `updater` VARCHAR(50) NOT NULL DEFAULT "系统" COMMENT '记录更新者',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '记录更新时间',   
  PRIMARY KEY (`id`),
  INDEX idx_guess_bet_match_id(`match_id`),
  INDEX idx_guess_user_id(`user_id`)
) ENGINE=INNODB AUTO_INCREMENT=180000000000 DEFAULT CHARSET=utf8 COMMENT='猜球投注表';

DROP TABLE IF EXISTS guess_bet_09;
CREATE TABLE `guess_bet_09` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '下注的用户id',
  `match_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '所下注的比赛id',
  `home_team_name` varchar(255) NOT NULL DEFAULT '' COMMENT '主队名',
  `home_team_logo` varchar(255) NOT NULL DEFAULT '' COMMENT '主队徽',
  `guest_team_name` varchar(255) NOT NULL DEFAULT '' COMMENT '客队名',
  `guest_team_logo` varchar(255) NOT NULL DEFAULT '' COMMENT '客队徽',
  `bet_item_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '下注时所选的下注项id',
  `bet_item_name` varchar(255) NOT NULL DEFAULT '' COMMENT '下注是所选的下注项的名称',
  `bet_points` INT(10) NOT NULL DEFAULT '0' COMMENT '所下的注数', 
  `odds` DECIMAL(5,2) NOT NULL DEFAULT '0.00' COMMENT '下注时的赔率', 
  `status` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '投注的状态，0代表未开奖、1代表已中奖、2代表未中奖',
  `win_bet_item_name` varchar(255) NOT NULL DEFAULT '' COMMENT '最终胜出的投注项名称',
  `win_points` INT(10) NULL DEFAULT '0' COMMENT '所赢得的总的积分',
  `pay_txn_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '所支付积分id',
  `recv_txn_id` BIGINT(20) NULL DEFAULT '0' COMMENT '所赢积分id',
  `phone_number` VARCHAR(20) NOT NULL DEFAULT "0" COMMENT '下注者电话',
  `delete_flag` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '删除标志位：0代表未删除，1代表已删除', 
  `creator` VARCHAR(50) NOT NULL DEFAULT "系统" COMMENT '记录添加者',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录添加时间',  
  `updater` VARCHAR(50) NOT NULL DEFAULT "系统" COMMENT '记录更新者',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '记录更新时间',   
  PRIMARY KEY (`id`),
  INDEX idx_guess_bet_match_id(`match_id`),
  INDEX idx_guess_user_id(`user_id`)
) ENGINE=INNODB AUTO_INCREMENT=190000000000 DEFAULT CHARSET=utf8 COMMENT='猜球投注表';

DROP TABLE IF EXISTS guess_bet_10;
CREATE TABLE `guess_bet_10` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '下注的用户id',
  `match_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '所下注的比赛id',
  `home_team_name` varchar(255) NOT NULL DEFAULT '' COMMENT '主队名',
  `home_team_logo` varchar(255) NOT NULL DEFAULT '' COMMENT '主队徽',
  `guest_team_name` varchar(255) NOT NULL DEFAULT '' COMMENT '客队名',
  `guest_team_logo` varchar(255) NOT NULL DEFAULT '' COMMENT '客队徽',
  `bet_item_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '下注时所选的下注项id',
  `bet_item_name` varchar(255) NOT NULL DEFAULT '' COMMENT '下注是所选的下注项的名称',
  `bet_points` INT(10) NOT NULL DEFAULT '0' COMMENT '所下的注数', 
  `odds` DECIMAL(5,2) NOT NULL DEFAULT '0.00' COMMENT '下注时的赔率', 
  `status` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '投注的状态，0代表未开奖、1代表已中奖、2代表未中奖',
  `win_bet_item_name` varchar(255) NOT NULL DEFAULT '' COMMENT '最终胜出的投注项名称',
  `win_points` INT(10) NULL DEFAULT '0' COMMENT '所赢得的总的积分',
  `pay_txn_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '所支付积分id',
  `recv_txn_id` BIGINT(20) NULL DEFAULT '0' COMMENT '所赢积分id',
  `phone_number` VARCHAR(20) NOT NULL DEFAULT "0" COMMENT '下注者电话',
  `delete_flag` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '删除标志位：0代表未删除，1代表已删除', 
  `creator` VARCHAR(50) NOT NULL DEFAULT "系统" COMMENT '记录添加者',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录添加时间',  
  `updater` VARCHAR(50) NOT NULL DEFAULT "系统" COMMENT '记录更新者',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '记录更新时间',   
  PRIMARY KEY (`id`),
  INDEX idx_guess_bet_match_id(`match_id`),
  INDEX idx_guess_user_id(`user_id`)
) ENGINE=INNODB AUTO_INCREMENT=200000000000 DEFAULT CHARSET=utf8 COMMENT='猜球投注表';

DROP TABLE IF EXISTS guess_bet_11;
CREATE TABLE `guess_bet_11` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '下注的用户id',
  `match_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '所下注的比赛id',
  `home_team_name` varchar(255) NOT NULL DEFAULT '' COMMENT '主队名',
  `home_team_logo` varchar(255) NOT NULL DEFAULT '' COMMENT '主队徽',
  `guest_team_name` varchar(255) NOT NULL DEFAULT '' COMMENT '客队名',
  `guest_team_logo` varchar(255) NOT NULL DEFAULT '' COMMENT '客队徽',
  `bet_item_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '下注时所选的下注项id',
  `bet_item_name` varchar(255) NOT NULL DEFAULT '' COMMENT '下注是所选的下注项的名称',
  `bet_points` INT(10) NOT NULL DEFAULT '0' COMMENT '所下的注数', 
  `odds` DECIMAL(5,2) NOT NULL DEFAULT '0.00' COMMENT '下注时的赔率', 
  `status` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '投注的状态，0代表未开奖、1代表已中奖、2代表未中奖',
  `win_bet_item_name` varchar(255) NOT NULL DEFAULT '' COMMENT '最终胜出的投注项名称',
  `win_points` INT(10) NULL DEFAULT '0' COMMENT '所赢得的总的积分',
  `pay_txn_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '所支付积分id',
  `recv_txn_id` BIGINT(20) NULL DEFAULT '0' COMMENT '所赢积分id',
  `phone_number` VARCHAR(20) NOT NULL DEFAULT "0" COMMENT '下注者电话',
  `delete_flag` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '删除标志位：0代表未删除，1代表已删除', 
  `creator` VARCHAR(50) NOT NULL DEFAULT "系统" COMMENT '记录添加者',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录添加时间',  
  `updater` VARCHAR(50) NOT NULL DEFAULT "系统" COMMENT '记录更新者',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '记录更新时间',   
  PRIMARY KEY (`id`),
  INDEX idx_guess_bet_match_id(`match_id`),
  INDEX idx_guess_user_id(`user_id`)
) ENGINE=INNODB AUTO_INCREMENT=210000000000 DEFAULT CHARSET=utf8 COMMENT='猜球投注表';

DROP TABLE IF EXISTS guess_bet_12;
CREATE TABLE `guess_bet_12` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '下注的用户id',
  `match_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '所下注的比赛id',
  `home_team_name` varchar(255) NOT NULL DEFAULT '' COMMENT '主队名',
  `home_team_logo` varchar(255) NOT NULL DEFAULT '' COMMENT '主队徽',
  `guest_team_name` varchar(255) NOT NULL DEFAULT '' COMMENT '客队名',
  `guest_team_logo` varchar(255) NOT NULL DEFAULT '' COMMENT '客队徽',
  `bet_item_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '下注时所选的下注项id',
  `bet_item_name` varchar(255) NOT NULL DEFAULT '' COMMENT '下注是所选的下注项的名称',
  `bet_points` INT(10) NOT NULL DEFAULT '0' COMMENT '所下的注数', 
  `odds` DECIMAL(5,2) NOT NULL DEFAULT '0.00' COMMENT '下注时的赔率', 
  `status` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '投注的状态，0代表未开奖、1代表已中奖、2代表未中奖',
  `win_bet_item_name` varchar(255) NOT NULL DEFAULT '' COMMENT '最终胜出的投注项名称',
  `win_points` INT(10) NULL DEFAULT '0' COMMENT '所赢得的总的积分',
  `pay_txn_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '所支付积分id',
  `recv_txn_id` BIGINT(20) NULL DEFAULT '0' COMMENT '所赢积分id',
  `phone_number` VARCHAR(20) NOT NULL DEFAULT "0" COMMENT '下注者电话',
  `delete_flag` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '删除标志位：0代表未删除，1代表已删除', 
  `creator` VARCHAR(50) NOT NULL DEFAULT "系统" COMMENT '记录添加者',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录添加时间',  
  `updater` VARCHAR(50) NOT NULL DEFAULT "系统" COMMENT '记录更新者',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '记录更新时间',   
  PRIMARY KEY (`id`),
  INDEX idx_guess_bet_match_id(`match_id`),
  INDEX idx_guess_user_id(`user_id`)
) ENGINE=INNODB AUTO_INCREMENT=220000000000 DEFAULT CHARSET=utf8 COMMENT='猜球投注表';

DROP TABLE IF EXISTS guess_bet_13;
CREATE TABLE `guess_bet_13` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '下注的用户id',
  `match_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '所下注的比赛id',
  `home_team_name` varchar(255) NOT NULL DEFAULT '' COMMENT '主队名',
  `home_team_logo` varchar(255) NOT NULL DEFAULT '' COMMENT '主队徽',
  `guest_team_name` varchar(255) NOT NULL DEFAULT '' COMMENT '客队名',
  `guest_team_logo` varchar(255) NOT NULL DEFAULT '' COMMENT '客队徽',
  `bet_item_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '下注时所选的下注项id',
  `bet_item_name` varchar(255) NOT NULL DEFAULT '' COMMENT '下注是所选的下注项的名称',
  `bet_points` INT(10) NOT NULL DEFAULT '0' COMMENT '所下的注数', 
  `odds` DECIMAL(5,2) NOT NULL DEFAULT '0.00' COMMENT '下注时的赔率', 
  `status` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '投注的状态，0代表未开奖、1代表已中奖、2代表未中奖',
  `win_bet_item_name` varchar(255) NOT NULL DEFAULT '' COMMENT '最终胜出的投注项名称',
  `win_points` INT(10) NULL DEFAULT '0' COMMENT '所赢得的总的积分',
  `pay_txn_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '所支付积分id',
  `recv_txn_id` BIGINT(20) NULL DEFAULT '0' COMMENT '所赢积分id',
  `phone_number` VARCHAR(20) NOT NULL DEFAULT "0" COMMENT '下注者电话',
  `delete_flag` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '删除标志位：0代表未删除，1代表已删除', 
  `creator` VARCHAR(50) NOT NULL DEFAULT "系统" COMMENT '记录添加者',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录添加时间',  
  `updater` VARCHAR(50) NOT NULL DEFAULT "系统" COMMENT '记录更新者',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '记录更新时间',   
  PRIMARY KEY (`id`),
  INDEX idx_guess_bet_match_id(`match_id`),
  INDEX idx_guess_user_id(`user_id`)
) ENGINE=INNODB AUTO_INCREMENT=230000000000 DEFAULT CHARSET=utf8 COMMENT='猜球投注表';

DROP TABLE IF EXISTS guess_bet_14;
CREATE TABLE `guess_bet_14` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '下注的用户id',
  `match_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '所下注的比赛id',
  `home_team_name` varchar(255) NOT NULL DEFAULT '' COMMENT '主队名',
  `home_team_logo` varchar(255) NOT NULL DEFAULT '' COMMENT '主队徽',
  `guest_team_name` varchar(255) NOT NULL DEFAULT '' COMMENT '客队名',
  `guest_team_logo` varchar(255) NOT NULL DEFAULT '' COMMENT '客队徽',
  `bet_item_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '下注时所选的下注项id',
  `bet_item_name` varchar(255) NOT NULL DEFAULT '' COMMENT '下注是所选的下注项的名称',
  `bet_points` INT(10) NOT NULL DEFAULT '0' COMMENT '所下的注数', 
  `odds` DECIMAL(5,2) NOT NULL DEFAULT '0.00' COMMENT '下注时的赔率', 
  `status` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '投注的状态，0代表未开奖、1代表已中奖、2代表未中奖',
  `win_bet_item_name` varchar(255) NOT NULL DEFAULT '' COMMENT '最终胜出的投注项名称',
  `win_points` INT(10) NULL DEFAULT '0' COMMENT '所赢得的总的积分',
  `pay_txn_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '所支付积分id',
  `recv_txn_id` BIGINT(20) NULL DEFAULT '0' COMMENT '所赢积分id',
  `phone_number` VARCHAR(20) NOT NULL DEFAULT "0" COMMENT '下注者电话',
  `delete_flag` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '删除标志位：0代表未删除，1代表已删除', 
  `creator` VARCHAR(50) NOT NULL DEFAULT "系统" COMMENT '记录添加者',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录添加时间',  
  `updater` VARCHAR(50) NOT NULL DEFAULT "系统" COMMENT '记录更新者',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '记录更新时间',   
  PRIMARY KEY (`id`),
  INDEX idx_guess_bet_match_id(`match_id`),
  INDEX idx_guess_user_id(`user_id`)
) ENGINE=INNODB AUTO_INCREMENT=240000000000 DEFAULT CHARSET=utf8 COMMENT='猜球投注表';

DROP TABLE IF EXISTS guess_bet_15;
CREATE TABLE `guess_bet_15` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '下注的用户id',
  `match_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '所下注的比赛id',
  `home_team_name` varchar(255) NOT NULL DEFAULT '' COMMENT '主队名',
  `home_team_logo` varchar(255) NOT NULL DEFAULT '' COMMENT '主队徽',
  `guest_team_name` varchar(255) NOT NULL DEFAULT '' COMMENT '客队名',
  `guest_team_logo` varchar(255) NOT NULL DEFAULT '' COMMENT '客队徽',
  `bet_item_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '下注时所选的下注项id',
  `bet_item_name` varchar(255) NOT NULL DEFAULT '' COMMENT '下注是所选的下注项的名称',
  `bet_points` INT(10) NOT NULL DEFAULT '0' COMMENT '所下的注数', 
  `odds` DECIMAL(5,2) NOT NULL DEFAULT '0.00' COMMENT '下注时的赔率', 
  `status` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '投注的状态，0代表未开奖、1代表已中奖、2代表未中奖',
  `win_bet_item_name` varchar(255) NOT NULL DEFAULT '' COMMENT '最终胜出的投注项名称',
  `win_points` INT(10) NULL DEFAULT '0' COMMENT '所赢得的总的积分',
  `pay_txn_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '所支付积分id',
  `recv_txn_id` BIGINT(20) NULL DEFAULT '0' COMMENT '所赢积分id',
  `phone_number` VARCHAR(20) NOT NULL DEFAULT "0" COMMENT '下注者电话',
  `delete_flag` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '删除标志位：0代表未删除，1代表已删除', 
  `creator` VARCHAR(50) NOT NULL DEFAULT "系统" COMMENT '记录添加者',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录添加时间',  
  `updater` VARCHAR(50) NOT NULL DEFAULT "系统" COMMENT '记录更新者',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '记录更新时间',   
  PRIMARY KEY (`id`),
  INDEX idx_guess_bet_match_id(`match_id`),
  INDEX idx_guess_user_id(`user_id`)
) ENGINE=INNODB AUTO_INCREMENT=250000000000 DEFAULT CHARSET=utf8 COMMENT='猜球投注表';

DROP TABLE IF EXISTS guess_bet_16;
CREATE TABLE `guess_bet_16` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '下注的用户id',
  `match_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '所下注的比赛id',
  `home_team_name` varchar(255) NOT NULL DEFAULT '' COMMENT '主队名',
  `home_team_logo` varchar(255) NOT NULL DEFAULT '' COMMENT '主队徽',
  `guest_team_name` varchar(255) NOT NULL DEFAULT '' COMMENT '客队名',
  `guest_team_logo` varchar(255) NOT NULL DEFAULT '' COMMENT '客队徽',
  `bet_item_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '下注时所选的下注项id',
  `bet_item_name` varchar(255) NOT NULL DEFAULT '' COMMENT '下注是所选的下注项的名称',
  `bet_points` INT(10) NOT NULL DEFAULT '0' COMMENT '所下的注数', 
  `odds` DECIMAL(5,2) NOT NULL DEFAULT '0.00' COMMENT '下注时的赔率', 
  `status` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '投注的状态，0代表未开奖、1代表已中奖、2代表未中奖',
  `win_bet_item_name` varchar(255) NOT NULL DEFAULT '' COMMENT '最终胜出的投注项名称',
  `win_points` INT(10) NULL DEFAULT '0' COMMENT '所赢得的总的积分',
  `pay_txn_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '所支付积分id',
  `recv_txn_id` BIGINT(20) NULL DEFAULT '0' COMMENT '所赢积分id',
  `phone_number` VARCHAR(20) NOT NULL DEFAULT "0" COMMENT '下注者电话',
  `delete_flag` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '删除标志位：0代表未删除，1代表已删除', 
  `creator` VARCHAR(50) NOT NULL DEFAULT "系统" COMMENT '记录添加者',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录添加时间',  
  `updater` VARCHAR(50) NOT NULL DEFAULT "系统" COMMENT '记录更新者',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '记录更新时间',   
  PRIMARY KEY (`id`),
  INDEX idx_guess_bet_match_id(`match_id`),
  INDEX idx_guess_user_id(`user_id`)
) ENGINE=INNODB AUTO_INCREMENT=260000000000 DEFAULT CHARSET=utf8 COMMENT='猜球投注表';

DROP TABLE IF EXISTS guess_bet_17;
CREATE TABLE `guess_bet_17` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '下注的用户id',
  `match_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '所下注的比赛id',
  `home_team_name` varchar(255) NOT NULL DEFAULT '' COMMENT '主队名',
  `home_team_logo` varchar(255) NOT NULL DEFAULT '' COMMENT '主队徽',
  `guest_team_name` varchar(255) NOT NULL DEFAULT '' COMMENT '客队名',
  `guest_team_logo` varchar(255) NOT NULL DEFAULT '' COMMENT '客队徽',
  `bet_item_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '下注时所选的下注项id',
  `bet_item_name` varchar(255) NOT NULL DEFAULT '' COMMENT '下注是所选的下注项的名称',
  `bet_points` INT(10) NOT NULL DEFAULT '0' COMMENT '所下的注数', 
  `odds` DECIMAL(5,2) NOT NULL DEFAULT '0.00' COMMENT '下注时的赔率', 
  `status` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '投注的状态，0代表未开奖、1代表已中奖、2代表未中奖',
  `win_bet_item_name` varchar(255) NOT NULL DEFAULT '' COMMENT '最终胜出的投注项名称',
  `win_points` INT(10) NULL DEFAULT '0' COMMENT '所赢得的总的积分',
  `pay_txn_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '所支付积分id',
  `recv_txn_id` BIGINT(20) NULL DEFAULT '0' COMMENT '所赢积分id',
  `phone_number` VARCHAR(20) NOT NULL DEFAULT "0" COMMENT '下注者电话',
  `delete_flag` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '删除标志位：0代表未删除，1代表已删除', 
  `creator` VARCHAR(50) NOT NULL DEFAULT "系统" COMMENT '记录添加者',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录添加时间',  
  `updater` VARCHAR(50) NOT NULL DEFAULT "系统" COMMENT '记录更新者',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '记录更新时间',   
  PRIMARY KEY (`id`),
  INDEX idx_guess_bet_match_id(`match_id`),
  INDEX idx_guess_user_id(`user_id`)
) ENGINE=INNODB AUTO_INCREMENT=270000000000 DEFAULT CHARSET=utf8 COMMENT='猜球投注表';

DROP TABLE IF EXISTS guess_bet_18;
CREATE TABLE `guess_bet_18` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '下注的用户id',
  `match_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '所下注的比赛id',
  `home_team_name` varchar(255) NOT NULL DEFAULT '' COMMENT '主队名',
  `home_team_logo` varchar(255) NOT NULL DEFAULT '' COMMENT '主队徽',
  `guest_team_name` varchar(255) NOT NULL DEFAULT '' COMMENT '客队名',
  `guest_team_logo` varchar(255) NOT NULL DEFAULT '' COMMENT '客队徽',
  `bet_item_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '下注时所选的下注项id',
  `bet_item_name` varchar(255) NOT NULL DEFAULT '' COMMENT '下注是所选的下注项的名称',
  `bet_points` INT(10) NOT NULL DEFAULT '0' COMMENT '所下的注数', 
  `odds` DECIMAL(5,2) NOT NULL DEFAULT '0.00' COMMENT '下注时的赔率', 
  `status` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '投注的状态，0代表未开奖、1代表已中奖、2代表未中奖',
  `win_bet_item_name` varchar(255) NOT NULL DEFAULT '' COMMENT '最终胜出的投注项名称',
  `win_points` INT(10) NULL DEFAULT '0' COMMENT '所赢得的总的积分',
  `pay_txn_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '所支付积分id',
  `recv_txn_id` BIGINT(20) NULL DEFAULT '0' COMMENT '所赢积分id',
  `phone_number` VARCHAR(20) NOT NULL DEFAULT "0" COMMENT '下注者电话',
  `delete_flag` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '删除标志位：0代表未删除，1代表已删除', 
  `creator` VARCHAR(50) NOT NULL DEFAULT "系统" COMMENT '记录添加者',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录添加时间',  
  `updater` VARCHAR(50) NOT NULL DEFAULT "系统" COMMENT '记录更新者',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '记录更新时间',   
  PRIMARY KEY (`id`),
  INDEX idx_guess_bet_match_id(`match_id`),
  INDEX idx_guess_user_id(`user_id`)
) ENGINE=INNODB AUTO_INCREMENT=280000000000 DEFAULT CHARSET=utf8 COMMENT='猜球投注表';

DROP TABLE IF EXISTS guess_bet_19;
CREATE TABLE `guess_bet_19` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '下注的用户id',
  `match_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '所下注的比赛id',
  `home_team_name` varchar(255) NOT NULL DEFAULT '' COMMENT '主队名',
  `home_team_logo` varchar(255) NOT NULL DEFAULT '' COMMENT '主队徽',
  `guest_team_name` varchar(255) NOT NULL DEFAULT '' COMMENT '客队名',
  `guest_team_logo` varchar(255) NOT NULL DEFAULT '' COMMENT '客队徽',
  `bet_item_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '下注时所选的下注项id',
  `bet_item_name` varchar(255) NOT NULL DEFAULT '' COMMENT '下注是所选的下注项的名称',
  `bet_points` INT(10) NOT NULL DEFAULT '0' COMMENT '所下的注数', 
  `odds` DECIMAL(5,2) NOT NULL DEFAULT '0.00' COMMENT '下注时的赔率', 
  `status` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '投注的状态，0代表未开奖、1代表已中奖、2代表未中奖',
  `win_bet_item_name` varchar(255) NOT NULL DEFAULT '' COMMENT '最终胜出的投注项名称',
  `win_points` INT(10) NULL DEFAULT '0' COMMENT '所赢得的总的积分',
  `pay_txn_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '所支付积分id',
  `recv_txn_id` BIGINT(20) NULL DEFAULT '0' COMMENT '所赢积分id',
  `phone_number` VARCHAR(20) NOT NULL DEFAULT "0" COMMENT '下注者电话',
  `delete_flag` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '删除标志位：0代表未删除，1代表已删除', 
  `creator` VARCHAR(50) NOT NULL DEFAULT "系统" COMMENT '记录添加者',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录添加时间',  
  `updater` VARCHAR(50) NOT NULL DEFAULT "系统" COMMENT '记录更新者',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '记录更新时间',   
  PRIMARY KEY (`id`),
  INDEX idx_guess_bet_match_id(`match_id`),
  INDEX idx_guess_user_id(`user_id`)
) ENGINE=INNODB AUTO_INCREMENT=290000000000 DEFAULT CHARSET=utf8 COMMENT='猜球投注表';

DROP TABLE IF EXISTS guess_bet_20;
CREATE TABLE `guess_bet_20` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '下注的用户id',
  `match_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '所下注的比赛id',
  `home_team_name` varchar(255) NOT NULL DEFAULT '' COMMENT '主队名',
  `home_team_logo` varchar(255) NOT NULL DEFAULT '' COMMENT '主队徽',
  `guest_team_name` varchar(255) NOT NULL DEFAULT '' COMMENT '客队名',
  `guest_team_logo` varchar(255) NOT NULL DEFAULT '' COMMENT '客队徽',
  `bet_item_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '下注时所选的下注项id',
  `bet_item_name` varchar(255) NOT NULL DEFAULT '' COMMENT '下注是所选的下注项的名称',
  `bet_points` INT(10) NOT NULL DEFAULT '0' COMMENT '所下的注数', 
  `odds` DECIMAL(5,2) NOT NULL DEFAULT '0.00' COMMENT '下注时的赔率', 
  `status` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '投注的状态，0代表未开奖、1代表已中奖、2代表未中奖',
  `win_bet_item_name` varchar(255) NOT NULL DEFAULT '' COMMENT '最终胜出的投注项名称',
  `win_points` INT(10) NULL DEFAULT '0' COMMENT '所赢得的总的积分',
  `pay_txn_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '所支付积分id',
  `recv_txn_id` BIGINT(20) NULL DEFAULT '0' COMMENT '所赢积分id',
  `phone_number` VARCHAR(20) NOT NULL DEFAULT "0" COMMENT '下注者电话',
  `delete_flag` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '删除标志位：0代表未删除，1代表已删除', 
  `creator` VARCHAR(50) NOT NULL DEFAULT "系统" COMMENT '记录添加者',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录添加时间',  
  `updater` VARCHAR(50) NOT NULL DEFAULT "系统" COMMENT '记录更新者',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '记录更新时间',   
  PRIMARY KEY (`id`),
  INDEX idx_guess_bet_match_id(`match_id`),
  INDEX idx_guess_user_id(`user_id`)
) ENGINE=INNODB AUTO_INCREMENT=300000000000 DEFAULT CHARSET=utf8 COMMENT='猜球投注表';

DROP TABLE IF EXISTS guess_bet_21;
CREATE TABLE `guess_bet_21` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '下注的用户id',
  `match_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '所下注的比赛id',
  `home_team_name` varchar(255) NOT NULL DEFAULT '' COMMENT '主队名',
  `home_team_logo` varchar(255) NOT NULL DEFAULT '' COMMENT '主队徽',
  `guest_team_name` varchar(255) NOT NULL DEFAULT '' COMMENT '客队名',
  `guest_team_logo` varchar(255) NOT NULL DEFAULT '' COMMENT '客队徽',
  `bet_item_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '下注时所选的下注项id',
  `bet_item_name` varchar(255) NOT NULL DEFAULT '' COMMENT '下注是所选的下注项的名称',
  `bet_points` INT(10) NOT NULL DEFAULT '0' COMMENT '所下的注数', 
  `odds` DECIMAL(5,2) NOT NULL DEFAULT '0.00' COMMENT '下注时的赔率', 
  `status` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '投注的状态，0代表未开奖、1代表已中奖、2代表未中奖',
  `win_bet_item_name` varchar(255) NOT NULL DEFAULT '' COMMENT '最终胜出的投注项名称',
  `win_points` INT(10) NULL DEFAULT '0' COMMENT '所赢得的总的积分',
  `pay_txn_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '所支付积分id',
  `recv_txn_id` BIGINT(20) NULL DEFAULT '0' COMMENT '所赢积分id',
  `phone_number` VARCHAR(20) NOT NULL DEFAULT "0" COMMENT '下注者电话',
  `delete_flag` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '删除标志位：0代表未删除，1代表已删除', 
  `creator` VARCHAR(50) NOT NULL DEFAULT "系统" COMMENT '记录添加者',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录添加时间',  
  `updater` VARCHAR(50) NOT NULL DEFAULT "系统" COMMENT '记录更新者',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '记录更新时间',   
  PRIMARY KEY (`id`),
  INDEX idx_guess_bet_match_id(`match_id`),
  INDEX idx_guess_user_id(`user_id`)
) ENGINE=INNODB AUTO_INCREMENT=310000000000 DEFAULT CHARSET=utf8 COMMENT='猜球投注表';

DROP TABLE IF EXISTS guess_bet_22;
CREATE TABLE `guess_bet_22` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '下注的用户id',
  `match_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '所下注的比赛id',
  `home_team_name` varchar(255) NOT NULL DEFAULT '' COMMENT '主队名',
  `home_team_logo` varchar(255) NOT NULL DEFAULT '' COMMENT '主队徽',
  `guest_team_name` varchar(255) NOT NULL DEFAULT '' COMMENT '客队名',
  `guest_team_logo` varchar(255) NOT NULL DEFAULT '' COMMENT '客队徽',
  `bet_item_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '下注时所选的下注项id',
  `bet_item_name` varchar(255) NOT NULL DEFAULT '' COMMENT '下注是所选的下注项的名称',
  `bet_points` INT(10) NOT NULL DEFAULT '0' COMMENT '所下的注数', 
  `odds` DECIMAL(5,2) NOT NULL DEFAULT '0.00' COMMENT '下注时的赔率', 
  `status` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '投注的状态，0代表未开奖、1代表已中奖、2代表未中奖',
  `win_bet_item_name` varchar(255) NOT NULL DEFAULT '' COMMENT '最终胜出的投注项名称',
  `win_points` INT(10) NULL DEFAULT '0' COMMENT '所赢得的总的积分',
  `pay_txn_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '所支付积分id',
  `recv_txn_id` BIGINT(20) NULL DEFAULT '0' COMMENT '所赢积分id',
  `phone_number` VARCHAR(20) NOT NULL DEFAULT "0" COMMENT '下注者电话',
  `delete_flag` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '删除标志位：0代表未删除，1代表已删除', 
  `creator` VARCHAR(50) NOT NULL DEFAULT "系统" COMMENT '记录添加者',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录添加时间',  
  `updater` VARCHAR(50) NOT NULL DEFAULT "系统" COMMENT '记录更新者',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '记录更新时间',   
  PRIMARY KEY (`id`),
  INDEX idx_guess_bet_match_id(`match_id`),
  INDEX idx_guess_user_id(`user_id`)
) ENGINE=INNODB AUTO_INCREMENT=320000000000 DEFAULT CHARSET=utf8 COMMENT='猜球投注表';

DROP TABLE IF EXISTS guess_bet_23;
CREATE TABLE `guess_bet_23` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '下注的用户id',
  `match_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '所下注的比赛id',
  `home_team_name` varchar(255) NOT NULL DEFAULT '' COMMENT '主队名',
  `home_team_logo` varchar(255) NOT NULL DEFAULT '' COMMENT '主队徽',
  `guest_team_name` varchar(255) NOT NULL DEFAULT '' COMMENT '客队名',
  `guest_team_logo` varchar(255) NOT NULL DEFAULT '' COMMENT '客队徽',
  `bet_item_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '下注时所选的下注项id',
  `bet_item_name` varchar(255) NOT NULL DEFAULT '' COMMENT '下注是所选的下注项的名称',
  `bet_points` INT(10) NOT NULL DEFAULT '0' COMMENT '所下的注数', 
  `odds` DECIMAL(5,2) NOT NULL DEFAULT '0.00' COMMENT '下注时的赔率', 
  `status` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '投注的状态，0代表未开奖、1代表已中奖、2代表未中奖',
  `win_bet_item_name` varchar(255) NOT NULL DEFAULT '' COMMENT '最终胜出的投注项名称',
  `win_points` INT(10) NULL DEFAULT '0' COMMENT '所赢得的总的积分',
  `pay_txn_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '所支付积分id',
  `recv_txn_id` BIGINT(20) NULL DEFAULT '0' COMMENT '所赢积分id',
  `phone_number` VARCHAR(20) NOT NULL DEFAULT "0" COMMENT '下注者电话',
  `delete_flag` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '删除标志位：0代表未删除，1代表已删除', 
  `creator` VARCHAR(50) NOT NULL DEFAULT "系统" COMMENT '记录添加者',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录添加时间',  
  `updater` VARCHAR(50) NOT NULL DEFAULT "系统" COMMENT '记录更新者',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '记录更新时间',   
  PRIMARY KEY (`id`),
  INDEX idx_guess_bet_match_id(`match_id`),
  INDEX idx_guess_user_id(`user_id`)
) ENGINE=INNODB AUTO_INCREMENT=330000000000 DEFAULT CHARSET=utf8 COMMENT='猜球投注表';

DROP TABLE IF EXISTS guess_bet_24;
CREATE TABLE `guess_bet_24` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '下注的用户id',
  `match_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '所下注的比赛id',
  `home_team_name` varchar(255) NOT NULL DEFAULT '' COMMENT '主队名',
  `home_team_logo` varchar(255) NOT NULL DEFAULT '' COMMENT '主队徽',
  `guest_team_name` varchar(255) NOT NULL DEFAULT '' COMMENT '客队名',
  `guest_team_logo` varchar(255) NOT NULL DEFAULT '' COMMENT '客队徽',
  `bet_item_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '下注时所选的下注项id',
  `bet_item_name` varchar(255) NOT NULL DEFAULT '' COMMENT '下注是所选的下注项的名称',
  `bet_points` INT(10) NOT NULL DEFAULT '0' COMMENT '所下的注数', 
  `odds` DECIMAL(5,2) NOT NULL DEFAULT '0.00' COMMENT '下注时的赔率', 
  `status` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '投注的状态，0代表未开奖、1代表已中奖、2代表未中奖',
  `win_bet_item_name` varchar(255) NOT NULL DEFAULT '' COMMENT '最终胜出的投注项名称',
  `win_points` INT(10) NULL DEFAULT '0' COMMENT '所赢得的总的积分',
  `pay_txn_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '所支付积分id',
  `recv_txn_id` BIGINT(20) NULL DEFAULT '0' COMMENT '所赢积分id',
  `phone_number` VARCHAR(20) NOT NULL DEFAULT "0" COMMENT '下注者电话',
  `delete_flag` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '删除标志位：0代表未删除，1代表已删除', 
  `creator` VARCHAR(50) NOT NULL DEFAULT "系统" COMMENT '记录添加者',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录添加时间',  
  `updater` VARCHAR(50) NOT NULL DEFAULT "系统" COMMENT '记录更新者',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '记录更新时间',   
  PRIMARY KEY (`id`),
  INDEX idx_guess_bet_match_id(`match_id`),
  INDEX idx_guess_user_id(`user_id`)
) ENGINE=INNODB AUTO_INCREMENT=340000000000 DEFAULT CHARSET=utf8 COMMENT='猜球投注表';

DROP TABLE IF EXISTS guess_bet_25;
CREATE TABLE `guess_bet_25` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '下注的用户id',
  `match_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '所下注的比赛id',
  `home_team_name` varchar(255) NOT NULL DEFAULT '' COMMENT '主队名',
  `home_team_logo` varchar(255) NOT NULL DEFAULT '' COMMENT '主队徽',
  `guest_team_name` varchar(255) NOT NULL DEFAULT '' COMMENT '客队名',
  `guest_team_logo` varchar(255) NOT NULL DEFAULT '' COMMENT '客队徽',
  `bet_item_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '下注时所选的下注项id',
  `bet_item_name` varchar(255) NOT NULL DEFAULT '' COMMENT '下注是所选的下注项的名称',
  `bet_points` INT(10) NOT NULL DEFAULT '0' COMMENT '所下的注数', 
  `odds` DECIMAL(5,2) NOT NULL DEFAULT '0.00' COMMENT '下注时的赔率', 
  `status` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '投注的状态，0代表未开奖、1代表已中奖、2代表未中奖',
  `win_bet_item_name` varchar(255) NOT NULL DEFAULT '' COMMENT '最终胜出的投注项名称',
  `win_points` INT(10) NULL DEFAULT '0' COMMENT '所赢得的总的积分',
  `pay_txn_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '所支付积分id',
  `recv_txn_id` BIGINT(20) NULL DEFAULT '0' COMMENT '所赢积分id',
  `phone_number` VARCHAR(20) NOT NULL DEFAULT "0" COMMENT '下注者电话',
  `delete_flag` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '删除标志位：0代表未删除，1代表已删除', 
  `creator` VARCHAR(50) NOT NULL DEFAULT "系统" COMMENT '记录添加者',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录添加时间',  
  `updater` VARCHAR(50) NOT NULL DEFAULT "系统" COMMENT '记录更新者',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '记录更新时间',   
  PRIMARY KEY (`id`),
  INDEX idx_guess_bet_match_id(`match_id`),
  INDEX idx_guess_user_id(`user_id`)
) ENGINE=INNODB AUTO_INCREMENT=350000000000 DEFAULT CHARSET=utf8 COMMENT='猜球投注表';

DROP TABLE IF EXISTS guess_bet_26;
CREATE TABLE `guess_bet_26` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '下注的用户id',
  `match_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '所下注的比赛id',
  `home_team_name` varchar(255) NOT NULL DEFAULT '' COMMENT '主队名',
  `home_team_logo` varchar(255) NOT NULL DEFAULT '' COMMENT '主队徽',
  `guest_team_name` varchar(255) NOT NULL DEFAULT '' COMMENT '客队名',
  `guest_team_logo` varchar(255) NOT NULL DEFAULT '' COMMENT '客队徽',
  `bet_item_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '下注时所选的下注项id',
  `bet_item_name` varchar(255) NOT NULL DEFAULT '' COMMENT '下注是所选的下注项的名称',
  `bet_points` INT(10) NOT NULL DEFAULT '0' COMMENT '所下的注数', 
  `odds` DECIMAL(5,2) NOT NULL DEFAULT '0.00' COMMENT '下注时的赔率', 
  `status` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '投注的状态，0代表未开奖、1代表已中奖、2代表未中奖',
  `win_bet_item_name` varchar(255) NOT NULL DEFAULT '' COMMENT '最终胜出的投注项名称',
  `win_points` INT(10) NULL DEFAULT '0' COMMENT '所赢得的总的积分',
  `pay_txn_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '所支付积分id',
  `recv_txn_id` BIGINT(20) NULL DEFAULT '0' COMMENT '所赢积分id',
  `phone_number` VARCHAR(20) NOT NULL DEFAULT "0" COMMENT '下注者电话',
  `delete_flag` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '删除标志位：0代表未删除，1代表已删除', 
  `creator` VARCHAR(50) NOT NULL DEFAULT "系统" COMMENT '记录添加者',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录添加时间',  
  `updater` VARCHAR(50) NOT NULL DEFAULT "系统" COMMENT '记录更新者',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '记录更新时间',   
  PRIMARY KEY (`id`),
  INDEX idx_guess_bet_match_id(`match_id`),
  INDEX idx_guess_user_id(`user_id`)
) ENGINE=INNODB AUTO_INCREMENT=360000000000 DEFAULT CHARSET=utf8 COMMENT='猜球投注表';

DROP TABLE IF EXISTS guess_bet_27;
CREATE TABLE `guess_bet_27` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '下注的用户id',
  `match_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '所下注的比赛id',
  `home_team_name` varchar(255) NOT NULL DEFAULT '' COMMENT '主队名',
  `home_team_logo` varchar(255) NOT NULL DEFAULT '' COMMENT '主队徽',
  `guest_team_name` varchar(255) NOT NULL DEFAULT '' COMMENT '客队名',
  `guest_team_logo` varchar(255) NOT NULL DEFAULT '' COMMENT '客队徽',
  `bet_item_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '下注时所选的下注项id',
  `bet_item_name` varchar(255) NOT NULL DEFAULT '' COMMENT '下注是所选的下注项的名称',
  `bet_points` INT(10) NOT NULL DEFAULT '0' COMMENT '所下的注数', 
  `odds` DECIMAL(5,2) NOT NULL DEFAULT '0.00' COMMENT '下注时的赔率', 
  `status` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '投注的状态，0代表未开奖、1代表已中奖、2代表未中奖',
  `win_bet_item_name` varchar(255) NOT NULL DEFAULT '' COMMENT '最终胜出的投注项名称',
  `win_points` INT(10) NULL DEFAULT '0' COMMENT '所赢得的总的积分',
  `pay_txn_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '所支付积分id',
  `recv_txn_id` BIGINT(20) NULL DEFAULT '0' COMMENT '所赢积分id',
  `phone_number` VARCHAR(20) NOT NULL DEFAULT "0" COMMENT '下注者电话',
  `delete_flag` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '删除标志位：0代表未删除，1代表已删除', 
  `creator` VARCHAR(50) NOT NULL DEFAULT "系统" COMMENT '记录添加者',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录添加时间',  
  `updater` VARCHAR(50) NOT NULL DEFAULT "系统" COMMENT '记录更新者',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '记录更新时间',   
  PRIMARY KEY (`id`),
  INDEX idx_guess_bet_match_id(`match_id`),
  INDEX idx_guess_user_id(`user_id`)
) ENGINE=INNODB AUTO_INCREMENT=370000000000 DEFAULT CHARSET=utf8 COMMENT='猜球投注表';

DROP TABLE IF EXISTS guess_bet_28;
CREATE TABLE `guess_bet_28` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '下注的用户id',
  `match_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '所下注的比赛id',
  `home_team_name` varchar(255) NOT NULL DEFAULT '' COMMENT '主队名',
  `home_team_logo` varchar(255) NOT NULL DEFAULT '' COMMENT '主队徽',
  `guest_team_name` varchar(255) NOT NULL DEFAULT '' COMMENT '客队名',
  `guest_team_logo` varchar(255) NOT NULL DEFAULT '' COMMENT '客队徽',
  `bet_item_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '下注时所选的下注项id',
  `bet_item_name` varchar(255) NOT NULL DEFAULT '' COMMENT '下注是所选的下注项的名称',
  `bet_points` INT(10) NOT NULL DEFAULT '0' COMMENT '所下的注数', 
  `odds` DECIMAL(5,2) NOT NULL DEFAULT '0.00' COMMENT '下注时的赔率', 
  `status` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '投注的状态，0代表未开奖、1代表已中奖、2代表未中奖',
  `win_bet_item_name` varchar(255) NOT NULL DEFAULT '' COMMENT '最终胜出的投注项名称',
  `win_points` INT(10) NULL DEFAULT '0' COMMENT '所赢得的总的积分',
  `pay_txn_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '所支付积分id',
  `recv_txn_id` BIGINT(20) NULL DEFAULT '0' COMMENT '所赢积分id',
  `phone_number` VARCHAR(20) NOT NULL DEFAULT "0" COMMENT '下注者电话',
  `delete_flag` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '删除标志位：0代表未删除，1代表已删除', 
  `creator` VARCHAR(50) NOT NULL DEFAULT "系统" COMMENT '记录添加者',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录添加时间',  
  `updater` VARCHAR(50) NOT NULL DEFAULT "系统" COMMENT '记录更新者',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '记录更新时间',   
  PRIMARY KEY (`id`),
  INDEX idx_guess_bet_match_id(`match_id`),
  INDEX idx_guess_user_id(`user_id`)
) ENGINE=INNODB AUTO_INCREMENT=380000000000 DEFAULT CHARSET=utf8 COMMENT='猜球投注表';

DROP TABLE IF EXISTS guess_bet_29;
CREATE TABLE `guess_bet_29` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '下注的用户id',
  `match_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '所下注的比赛id',
  `home_team_name` varchar(255) NOT NULL DEFAULT '' COMMENT '主队名',
  `home_team_logo` varchar(255) NOT NULL DEFAULT '' COMMENT '主队徽',
  `guest_team_name` varchar(255) NOT NULL DEFAULT '' COMMENT '客队名',
  `guest_team_logo` varchar(255) NOT NULL DEFAULT '' COMMENT '客队徽',
  `bet_item_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '下注时所选的下注项id',
  `bet_item_name` varchar(255) NOT NULL DEFAULT '' COMMENT '下注是所选的下注项的名称',
  `bet_points` INT(10) NOT NULL DEFAULT '0' COMMENT '所下的注数', 
  `odds` DECIMAL(5,2) NOT NULL DEFAULT '0.00' COMMENT '下注时的赔率', 
  `status` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '投注的状态，0代表未开奖、1代表已中奖、2代表未中奖',
  `win_bet_item_name` varchar(255) NOT NULL DEFAULT '' COMMENT '最终胜出的投注项名称',
  `win_points` INT(10) NULL DEFAULT '0' COMMENT '所赢得的总的积分',
  `pay_txn_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '所支付积分id',
  `recv_txn_id` BIGINT(20) NULL DEFAULT '0' COMMENT '所赢积分id',
  `phone_number` VARCHAR(20) NOT NULL DEFAULT "0" COMMENT '下注者电话',
  `delete_flag` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '删除标志位：0代表未删除，1代表已删除', 
  `creator` VARCHAR(50) NOT NULL DEFAULT "系统" COMMENT '记录添加者',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录添加时间',  
  `updater` VARCHAR(50) NOT NULL DEFAULT "系统" COMMENT '记录更新者',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '记录更新时间',   
  PRIMARY KEY (`id`),
  INDEX idx_guess_bet_match_id(`match_id`),
  INDEX idx_guess_user_id(`user_id`)
) ENGINE=INNODB AUTO_INCREMENT=390000000000 DEFAULT CHARSET=utf8 COMMENT='猜球投注表';

DROP TABLE IF EXISTS guess_bet_30;
CREATE TABLE `guess_bet_30` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '下注的用户id',
  `match_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '所下注的比赛id',
  `home_team_name` varchar(255) NOT NULL DEFAULT '' COMMENT '主队名',
  `home_team_logo` varchar(255) NOT NULL DEFAULT '' COMMENT '主队徽',
  `guest_team_name` varchar(255) NOT NULL DEFAULT '' COMMENT '客队名',
  `guest_team_logo` varchar(255) NOT NULL DEFAULT '' COMMENT '客队徽',
  `bet_item_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '下注时所选的下注项id',
  `bet_item_name` varchar(255) NOT NULL DEFAULT '' COMMENT '下注是所选的下注项的名称',
  `bet_points` INT(10) NOT NULL DEFAULT '0' COMMENT '所下的注数', 
  `odds` DECIMAL(5,2) NOT NULL DEFAULT '0.00' COMMENT '下注时的赔率', 
  `status` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '投注的状态，0代表未开奖、1代表已中奖、2代表未中奖',
  `win_bet_item_name` varchar(255) NOT NULL DEFAULT '' COMMENT '最终胜出的投注项名称',
  `win_points` INT(10) NULL DEFAULT '0' COMMENT '所赢得的总的积分',
  `pay_txn_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '所支付积分id',
  `recv_txn_id` BIGINT(20) NULL DEFAULT '0' COMMENT '所赢积分id',
  `phone_number` VARCHAR(20) NOT NULL DEFAULT "0" COMMENT '下注者电话',
  `delete_flag` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '删除标志位：0代表未删除，1代表已删除', 
  `creator` VARCHAR(50) NOT NULL DEFAULT "系统" COMMENT '记录添加者',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录添加时间',  
  `updater` VARCHAR(50) NOT NULL DEFAULT "系统" COMMENT '记录更新者',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '记录更新时间',   
  PRIMARY KEY (`id`),
  INDEX idx_guess_bet_match_id(`match_id`),
  INDEX idx_guess_user_id(`user_id`)
) ENGINE=INNODB AUTO_INCREMENT=400000000000 DEFAULT CHARSET=utf8 COMMENT='猜球投注表';

DROP TABLE IF EXISTS guess_bet_31;
CREATE TABLE `guess_bet_31` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '下注的用户id',
  `match_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '所下注的比赛id',
  `home_team_name` varchar(255) NOT NULL DEFAULT '' COMMENT '主队名',
  `home_team_logo` varchar(255) NOT NULL DEFAULT '' COMMENT '主队徽',
  `guest_team_name` varchar(255) NOT NULL DEFAULT '' COMMENT '客队名',
  `guest_team_logo` varchar(255) NOT NULL DEFAULT '' COMMENT '客队徽',
  `bet_item_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '下注时所选的下注项id',
  `bet_item_name` varchar(255) NOT NULL DEFAULT '' COMMENT '下注是所选的下注项的名称',
  `bet_points` INT(10) NOT NULL DEFAULT '0' COMMENT '所下的注数', 
  `odds` DECIMAL(5,2) NOT NULL DEFAULT '0.00' COMMENT '下注时的赔率', 
  `status` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '投注的状态，0代表未开奖、1代表已中奖、2代表未中奖',
  `win_bet_item_name` varchar(255) NOT NULL DEFAULT '' COMMENT '最终胜出的投注项名称',
  `win_points` INT(10) NULL DEFAULT '0' COMMENT '所赢得的总的积分',
  `pay_txn_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '所支付积分id',
  `recv_txn_id` BIGINT(20) NULL DEFAULT '0' COMMENT '所赢积分id',
  `phone_number` VARCHAR(20) NOT NULL DEFAULT "0" COMMENT '下注者电话',
  `delete_flag` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '删除标志位：0代表未删除，1代表已删除', 
  `creator` VARCHAR(50) NOT NULL DEFAULT "系统" COMMENT '记录添加者',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录添加时间',  
  `updater` VARCHAR(50) NOT NULL DEFAULT "系统" COMMENT '记录更新者',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '记录更新时间',   
  PRIMARY KEY (`id`),
  INDEX idx_guess_bet_match_id(`match_id`),
  INDEX idx_guess_user_id(`user_id`)
) ENGINE=INNODB AUTO_INCREMENT=410000000000 DEFAULT CHARSET=utf8 COMMENT='猜球投注表';



